version: '3.9'

services:
  api:
    container_name: api
    build:
      context: ./src/backend
      dockerfile: ../../compose/local/backend/Dockerfile
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - /myapp/node_modules/
      - ./src/backend:/myapp/
  mongodb:
    container_name: app_db
    image: mongo
    volumes:
      - ./database/:/data/db/
    logging:
      driver: none

  web:
    container_name: app_web
    build:
      context: ./src/frontend
      dockerfile: ../../compose/local/frontend/Dockerfile
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./:/app/
    ports:
      - '3000:3000'

volumes:
  js_dependencies:
