version: '3.9'

services:
  api:
    container_name: api
    build:
      context: ./src/backend
      dockerfile: ../../compose/local/backend/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - js_dependencies:/myapp/node_modules
      - ./src/backend:/myapp/

volumes:
  js_dependencies:
